---
- name: Install and configure nextcloud
  hosts: all
  become: true

  roles:
    - myckakamil.snmpd

  pre_tasks:
    - name: Load variables
      ansible.builtin.include_vars: vars/config.yaml
    - name: Load vault
      ansible.builtin.include_vars: vars/vault.yaml
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
  tags: always

  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name:
          - apache2
          - mariadb-client
          - mariadb-server
          - libapache2-mod-php
          - php-gd
          - php-mysql
          - php-curl
          - php-mbstring
          - php-intl
          - php-gmp
          - php-xml
          - php-imagick
          - php-zip
          - python3-pymysql
          - unzip
        state: present

    - name: Move apache2 virtual host template
      ansible.builtin.template:
        src: templates/nextcloud.conf.j2
        dest: /etc/apache2/sites-available/000-default.conf
        owner: www-data
        group: www-data
        mode: "0644"
      notify: Restart apache2

    - name: Ensure apache2 is started and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true

    - name: Ensure mariadb is started and enabled
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

    - name: Create Nextcloud database
      community.mysql.mysql_db:
        name: "{{ nextcloud_db_name }}"
        state: present
        encoding: utf8mb4
        collation: utf8mb4_general_ci
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Create Nextcloud DB user
      community.mysql.mysql_user:
        name: "{{ nextcloud_db_user }}"
        password: "{{ nextcloud_db_password }}"
        host: localhost
        priv: "{{ nextcloud_db_name }}.*:ALL"
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Check if nextcloud is already downloaded
      ansible.builtin.stat:
        path: /opt/nextcloud-32.0.1.zip
      register: nextcloud_downloaded

    - name: Download nextcloud archive
      ansible.builtin.get_url:
        url: https://download.nextcloud.com/server/releases/nextcloud-32.0.1.zip
        dest: /opt/
        owner: root
        group: root
        mode: "0755"
      when: not nextcloud_downloaded.stat.exists

    - name: Unzip nextcloud archive
      ansible.builtin.unarchive:
        src: /opt/nextcloud-32.0.1.zip
        dest: /var/www/html/
        remote_src: true
        creates: /var/www/html/nextcloud/robots.txt
        owner: www-data
        group: www-data
        mode: "0775"

    - name: Create folder for data
      ansible.builtin.file:
        path: /var/www/html/nextcloud/data
        state: directory
        owner: www-data
        group: www-data
        mode: '0775'

  handlers:
    - name: Load handlers
      ansible.builtin.import_tasks: tasks/handlers.yaml
